Fix errors due to using CFLAGS -Wall -Werror
vmod_digest.c: In function 'vmod_digest_alpha_init':
vmod_digest.c:79:3: error: array subscript has type 'char' [-Werror=char-subscripts]
vmod_digest.c: In function 'vmod_hmac_generic':
vmod_digest.c:265:9: error: pointer targets in assignment differ in signedness [-Werror=pointer-sign]
vmod_digest.c:269:2: error: pointer targets in passing argument 1 of 'sprintf' differ in signedness [-Werror=pointer-sign]
In file included from vmod_digest.c:36:0:
/usr/include/stdio.h:361:12: note: expected 'char * restrict' but argument is of type 'unsigned char *'
vmod_digest.c:272:3: error: pointer targets in passing argument 1 of 'sprintf' differ in signedness [-Werror=pointer-sign]
In file included from vmod_digest.c:36:0:
/usr/include/stdio.h:361:12: note: expected 'char * restrict' but argument is of type 'unsigned char *'
vmod_digest.c:277:2: error: pointer targets in return differ in signedness [-Werror=pointer-sign]
vmod_digest.c:235:9: error: unused variable 'maclen' [-Werror=unused-variable]